### ISSUE TITLE
docker_godwoken_1 exited with code 101

### ISSUE THREAD

**Issue by Flouse** [RetricSu/godwoken-kicker#10]
```
sync new block #416 success
godwoken_1             | produce new block #417 (txs: 0, deposits: 0, staled txs: 0, staled withdrawals: 0)
godwoken_1             | produce new block #417 (txs: 0, deposits: 0, staled txs: 0, staled withdrawals: 0)
godwoken_1             | Poll transactions: 2
godwoken_1             | sync new block #417 success
godwoken_1             | Poll transactions: 2
godwoken_1             | thread 'main' panicked at 'assertion failed: `(left == right)`
godwoken_1             |   left: `(417, [77, 205, 134, 173, 194, 50, 215, 64, 39, 86, 47, 67, 211, 172, 105, 33, 63, 119, 143, 78, 208, 33, 210, 76, 191, 158, 127, 239, 87, 208, 3, 171])`,
godwoken_1             |  right: `(418, [62, 220, 91, 108, 148, 81, 188, 25, 121, 64, 195, 41, 141, 77, 110, 178, 196, 92, 14, 100, 157, 234, 251, 200, 198, 103, 99, 250, 86, 105, 77, 61])`: new l2block must be the successor of the tip', crates/chain/src/chain.rs:441:9
godwoken_1             | stack backtrace:
godwoken_1             |    0: rust_begin_unwind
godwoken_1             |              at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
godwoken_1             |    1: core::panicking::panic_fmt
godwoken_1             |              at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
godwoken_1             |    2: gw_chain::chain::Chain::process_block
godwoken_1             |              at ./crates/chain/src/chain.rs:441:9
godwoken_1             |    3: gw_chain::chain::Chain::update_l1action
godwoken_1             |              at ./crates/chain/src/chain.rs:231:50
godwoken_1             |    4: gw_chain::chain::Chain::sync
godwoken_1             |              at ./crates/chain/src/chain.rs:385:25
godwoken_1             |    5: gw_block_producer::poller::ChainUpdater::update_single::{{closure}}
godwoken_1             |              at ./crates/block-producer/src/poller.rs:182:9
godwoken_1             |    6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
godwoken_1             |              at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/mod.rs:80:19
godwoken_1             |    7: gw_block_producer::poller::ChainUpdater::update::{{closure}}
godwoken_1             |              at ./crates/block-producer/src/poller.rs:121:13
godwoken_1             |    8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
godwoken_1             |              at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/mod.rs:80:19
godwoken_1             |    9: gw_block_producer::poller::ChainUpdater::inner_poll_loop::{{closure}}
godwoken_1             |              at ./crates/block-producer/src/poller.rs:112:17
godwoken_1             |   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
godwoken_1             |              at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/mod.rs:80:19
godwoken_1             |   11: gw_block_producer::poller::ChainUpdater::poll_loop::{{closure}}
godwoken_1             |              at ./crates/block-producer/src/poller.rs:58:29
godwoken_1             |   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
godwoken_1             |              at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/mod.rs:80:19
godwoken_1             |   13: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
godwoken_1             |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/fuse.rs:86:37
godwoken_1             |   14: <core::pin::Pin<P> as core::future::future::Future>::poll
godwoken_1             |              at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/future.rs:119:9
godwoken_1             |   15: futures_util::future::future::FutureExt::poll_unpin
godwoken_1             |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/mod.rs:562:9
godwoken_1             |   16: godwoken::run::{{closure}}::{{closure}}::{{closure}}
godwoken_1             |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/async_await/select_mod.rs:326:13
godwoken_1             |   17: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
godwoken_1             |              at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:269:13
godwoken_1             |   18: godwoken::run::{{closure}}::{{closure}}
godwoken_1             |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/async_await/select_mod.rs:326:13
godwoken_1             |   19: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
godwoken_1             |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/poll_fn.rs:55:9
godwoken_1             |   20: godwoken::run::{{closure}}
godwoken_1             |              at ./crates/block-producer/src/main.rs:190:9
godwoken_1             |   21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
godwoken_1             |              at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/mod.rs:80:19
godwoken_1             |   22: async_io::driver::block_on
godwoken_1             |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/async-io-1.3.1/src/driver.rs:142:33
godwoken_1             |   23: godwoken::run
godwoken_1             |              at ./crates/block-producer/src/main.rs:189:5
godwoken_1             |   24: godwoken::main
godwoken_1             |              at ./crates/block-producer/src/main.rs:222:5
godwoken_1             |   25: core::ops::function::FnOnce::call_once
godwoken_1             |              at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
godwoken_1             | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I have kept the containers `docker-compose up` over 30 hours, and I found the above error in `docker_godwoken_1` container.
I restarted the `docker_godwoken_1` container and the same error came out again.

**Comment by Flouse** [comment]
I have used `make start-f` to deploy a new godwoken chain.

**Comment by RetricSu** [comment]
would love to know what version of godwoken is used here.

and is there any activate transactions ( like deposit \ l2 tx \ withdraw\ etc) happened durning these 30 hours to trigger such an error?

**Comment by Flouse** [comment]
> would love to know what version of godwoken is used here.
### Version: godwoken @ 26d15db
#### commit 26d15dbe42d15ad902593fcc89cf82b1ccc18d66 (HEAD)

> 
> and is there any activate transactions ( like deposit \ l2 tx \ withdraw\ etc) happened durning these 30 hours to trigger such an error?
Yes, I have followed the steps in [README.md](https://github.com/RetricSu/godwoken-kicker/blob/88e1741ab56c65bdab8f5124ecbc28c48cde7e93/README.md).
Hence there should be activate transactions ( like deposit, deploy contract etc.) happened.

**Comment by Flouse** [comment]
1. `make stop`
2. `make start`
3. Container `docker_godwoken_1` was failed to restart:

## Logs:

> sync new block #1552 success
sync new block #1553 success
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `(882, [141, 109, 121, 111, 190, 145, 35, 28, 50, 69, 135, 178, 98, 159, 185, 241, 227, 209, 148, 79, 172, 226, 207, 166, 218, 127, 120, 12, 62, 29, 183, 87])`,
 right: `(1554, [120, 127, 100, 104, 247, 5, 53, 235, 247, 250, 202, 37, 170, 242, 98, 130, 42, 211, 203, 63, 77, 8, 215, 235, 137, 113, 131, 86, 89, 182, 75, 155])`: new l2block must be the successor of the tip', crates/chain/src/chain.rs:441:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: gw_chain::chain::Chain::process_block
             at ./crates/chain/src/chain.rs:441:9
   3: gw_chain::chain::Chain::update_l1action
             at ./crates/chain/src/chain.rs:231:50
   4: gw_chain::chain::Chain::sync
             at ./crates/chain/src/chain.rs:385:25
   5: gw_block_producer::poller::ChainUpdater::update_single::{{closure}}
             at ./crates/block-producer/src/poller.rs:182:9
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/mod.rs:80:19
   7: gw_block_producer::poller::ChainUpdater::update::{{closure}}
             at ./crates/block-producer/src/poller.rs:121:13
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/mod.rs:80:19
   9: gw_block_producer::poller::ChainUpdater::inner_poll_loop::{{closure}}
             at ./crates/block-producer/src/poller.rs:112:17
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/mod.rs:80:19
  11: gw_block_producer::poller::ChainUpdater::poll_loop::{{closure}}
             at ./crates/block-producer/src/poller.rs:58:29
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/mod.rs:80:19
  13: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/fuse.rs:86:37
  14: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/future.rs:119:9
  15: futures_util::future::future::FutureExt::poll_unpin
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/mod.rs:562:9
  16: godwoken::run::{{closure}}::{{closure}}::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/async_await/select_mod.rs:326:13
  17: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:269:13
  18: godwoken::run::{{closure}}::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/async_await/select_mod.rs:326:13
  19: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/poll_fn.rs:55:9
  20: godwoken::run::{{closure}}
             at ./crates/block-producer/src/main.rs:190:9
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/mod.rs:80:19
  22: async_io::driver::block_on
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/async-io-1.3.1/src/driver.rs:142:33
  23: godwoken::run
             at ./crates/block-producer/src/main.rs:189:5
  24: godwoken::main
             at ./crates/block-producer/src/main.rs:222:5
  25: core::ops::function::FnOnce::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by RetricSu** [comment]
looks like it might be a issue with the old chain data. so when you do `make stop` then `make start`, the layer 1 ckb chain keep the old chain data and reuse it, thus layer2 godwoken chain also reuse the  old data, but somehow the new block in godwoken did not successful produced base on old data. 

clear the old data (run `make clear`) should make `docker_godwoken_1 ` restart again. but it did not fix this issue. unfortunately I have not encounter this problem so far, if you are able to reproduce this issue, pls let me know.

**Comment by Flouse** [comment]
I can't reproduce this issue.
let's move on to the new version of godwoken.

**Comment by RetricSu** [comment]
the issue is caused by not using real state-validator, version after `v0.3.0-rc2` should be fine.
