### ISSUE TITLE
Instant finality

### ISSUE THREAD

**Issue by Kuzirashi** [RetricSu/godwoken-kicker#134]
It seems that transactions are processed in 1 minute block intervals (Iike on testnet) in godwoken-kicker. 

Is it possible to use Instant Finality like previously in kicker where you send a transaction and it's instantly included?

Previously it was possible to deploy multiple smart contracts to godwoken-kicker devnet in seconds, and now it can take 20 minutes. 

Thanks for help @RetricSu

**Comment by RetricSu** [comment]
what version?  maybe you hit the rate limit, not instant finality https://github.com/nervosnetwork/godwoken-polyjuice/issues/102#issuecomment-986586449
