### ISSUE TITLE
sed: can't read /code/godwoken/config.toml: No such file or directory after make start

### ISSUE THREAD

**Issue by Kuzirashi** [RetricSu/godwoken-kicker#19]
After running:
```
make init
make start
```

Godwoken fails to start with following error:
```
godwoken_1             | sed: can't read /code/godwoken/config.toml: No such file or directory
```

Full log: https://gist.github.com/Kuzirashi/e2ad089f75384833190f464c195663d7

Version: commit 1a7791ccdae42a11e7be93d90e0a7c458736ffbd from master

**Comment by RetricSu** [comment]
can you confirm that this is fix with https://github.com/RetricSu/godwoken-kicker/commit/2bafd072723c3665a43c33b724c37c2bb8af5921 ?

**Comment by Kuzirashi** [comment]
Fixed.
