### ISSUE TITLE
Not possible to deploy bigger compiled smart-contracts than 8KB

### ISSUE THREAD

**Issue by Kuzirashi** [RetricSu/godwoken-kicker#2]
It's not possible to deploy smart-contract code bigger than 8KB (default Node.js limit for header size in Node versions < 14). If you try to deploy bigger contract you get: "431 Request Header Fields Too Large".

Fix is to change "start" command in "godwoken-kicker/godwoken-examples/packages/runner/package.json (git)" to:
```
"start": "LUMOS_CONFIG_FILE=./configs/lumos-config.json MODE=docker-compose ts-node-dev --max-http-header-size=1000000 -- ./src/index",
```

**Comment by RetricSu** [comment]
ok, should be a quick fix.

**Comment by Kuzirashi** [comment]
Solved.
