### ISSUE TITLE
Kicker cannot run on Windows.

### ISSUE THREAD

**Issue by keroro520** [RetricSu/godwoken-kicker#208]
Currently, Kicker cannot run on Windows. We should note this platform-related issue in README.

**Comment by ShookLyngs** [comment]
Tried to run Kicker on Windows 11 and failed.

The downloading was fine, but when running containers, docker reported a `container for service "godwoken" is unhealthy`. 
And container `docker-godwoken-1` logs this:
```
exec /var/lib/layer2/entrypoint.sh: no such file or directory
```
