### ISSUE TITLE
should the execution time meet with the local system time?

### ISSUE THREAD

**Issue by BourneNeo** [RetricSu/godwoken-kicker#234]
**environment:**
Linux DESKTOP-Q1QBGQQ 5.10.102.1-microsoft-standard-WSL2 https://github.com/RetricSu/godwoken-kicker/issues/1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**prerequisites:**
Docker version 20.10.12, build e91ed57
docker-compose version 1.29.2, build 5becea4c

**details:**
![image](https://user-images.githubusercontent.com/18527271/163968134-24daa13f-594d-46a5-88fd-b52851f04e20.png)

**Comment by Flouse** [comment]
The Z stands for the Zero timezone, as it is offset by 0 from the Coordinated Universal Time (UTC).

**Comment by BourneNeo** [comment]
> The Z stands for the Zero timezone, as it is offset by 0 from the Coordinated Universal Time (UTC).
ok
