### ISSUE TITLE
[v1.1] update to v1.1 start at the 1st time report  web3  Container unhealthy error, re-start succeeded

### ISSUE THREAD

**Issue by BourneNeo** [RetricSu/godwoken-kicker#246]
![image](https://user-images.githubusercontent.com/18527271/167591725-9e721bad-54d5-4e9b-bcaf-f4d99145fe02.png)

$ kicker ps
[new.log](https://github.com/RetricSu/godwoken-kicker/files/8660055/new.log)
:> docker-compose -f docker/docker-compose.yml ps

                 Name                                Command                  State                           Ports                     
----------------------------------------------------------------------------------------------------------------------------------------
docker_check-ckb-started-successfully_1   /entrypoint.sh http://ckb: ...   Exit 0                                                       
docker_ckb-indexer_1                      /bin/ckb-indexer -c http:/ ...   Up             0.0.0.0:8116->8116/tcp                        
docker_ckb-miner_1                        /bin/docker-entrypoint.sh  ...   Up             8114/tcp, 8115/tcp                            
docker_ckb_1                              /bin/docker-entrypoint.sh  ...   Up             0.0.0.0:8114->8114/tcp, 0.0.0.0:8115->8115/tcp
docker_godwoken_1                         /var/lib/layer2/entrypoint.sh    Up (healthy)   0.0.0.0:8119->8119/tcp, 0.0.0.0:8120->8120/tcp
docker_postgres_1                         docker-entrypoint.sh postgres    Up             0.0.0.0:5432->5432/tcp                        
docker_redis_1                            docker-entrypoint.sh redis ...   Up             0.0.0.0:6379->6379/tcp

**Comment by keroro520** [comment]
![2022-05-11 at 10 59 AM](https://user-images.githubusercontent.com/1870648/167760162-ff95703f-4337-4c81-a623-60b214dd656b.jpg)

It's docker software trouble.
