### ISSUE TITLE
can't start kicker, for "web3-indexer  Container  is unhealthy"

### ISSUE THREAD

**Issue by BourneNeo** [RetricSu/godwoken-kicker#261]
![image](https://user-images.githubusercontent.com/18527271/170630503-43456706-c8ce-49e5-9743-1c49bf217d24.png)
[ps+log.log](https://github.com/RetricSu/godwoken-kicker/files/8783983/ps%2Blog.log)

**Comment by BourneNeo** [comment]
recovered when restarted docker-desktop, maybe cause of docker-desktop

**Comment by keroro520** [comment]
After cleaning and restarting, it starts success.
