### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by keroro520** [RetricSu/godwoken-kicker#264]
# Contributing to Godwoken-Kicker

We use the [Trunk-Based Development Flow](https://trunkbaseddevelopment.com/branch-for-release/). We maintain only one long-lived branch, the "main" branch. 

### Submiting Pull Request

- Most of the time, you should submit PRs to the "main" branch.
- When submitting PR and it should be noted in the release note, please write down the release note in the PR description and mark the PR with "release-note" label
- When submiting a PR and it brings breaking-changs, please please write down the release note in the PR description and mark the PR with "release-note" and "breaking-change" label

### Release Process

- At the scheduled time, checkouts a "rc-" branch from the current "main" branch
- As for non-emergence commits and patches, submit PRs to the "main" branch, then cherry-pick commits from "main" to "rc-"
- As for emergence hotfix ...... Godwoken-Kicker should not have emergence hotfix ... when it occurs, make PRs to "rc-hotfix" branch, then cherry-pick to "main" branch.
- Since Godwoken-Kicker is not a production project, we don't have to maintain a CHANGELOG.md.

**Comment by keroro520** [comment]
Currently, this repo doesn't have "main" branch but "develop". So I plan to 

1. rename the "compatibility-changes" branch to "main"
2. create a ”v0.10" branch from the "develop" branch, then delete the "develop“ branch.

@Flouse @RetricSu What do you think?

**Comment by Flouse** [comment]
> Currently, this repo doesn't have "main" branch but "develop". So I plan to 
> 
> 1. rename the "compatibility-changes" branch to "main"
> 2. create a ”v0.10" branch from the "develop" branch, then delete the "develop“ branch.
> 
> @Flouse @RetricSu What do you think?

LGTM

**Comment by keroro520** [comment]
Oh, I missed the "master" branch.

1. Firstly, merge "develop" into "master" and delete "develop"
2. Then, merge "compatibility-changes" into "master" while keep "compatibility-changes"

is that so? @RetricSu

**Comment by RetricSu** [comment]
> Oh, I missed the "master" branch.
> 
> 1. Firstly, merge "develop" into "master" and delete "develop"
> 2. Then, merge "compatibility-changes" into "master" while keep "compatibility-changes"
> 
> is that so? @RetricSu

yes

**Comment by keroro520** [comment]
> 1. Firstly, merge "develop" into "master" and delete "develop"
> 2. Then, merge "compatibility-changes" into "master" while keep "compatibility-changes"

1. https://github.com/RetricSu/godwoken-kicker/pull/268
2. https://github.com/RetricSu/godwoken-kicker/pull/269

**Comment by keroro520** [comment]
We already have [tag v0.9.0-rc3](https://github.com/RetricSu/godwoken-kicker/tree/v0.9.0-rc3). So I plan to create a branch named "rc-0.10.0" from e8a8c7b [Merge develop into master #268](https://github.com/RetricSu/godwoken-kicker/pull/268), tracking Godwoken v0
