### ISSUE TITLE
[v1.2]failed tx (out of gas) have not been input into the blockchain

### ISSUE THREAD

**Issue by gpBlockchain** [RetricSu/godwoken-kicker#279]
### env

guopenglin@192 godwoken-kicker % git log --format="%H" -n 1
0577349c5d9b56cd92f8200d18e541c72d1068bb

#### code 
function testEvent(uint256 begin,uint rd,uint256 mid ,uint end) public {

        for(uint256 i=0;i<begin;i++){
            emit blockHashEvent(bytes32(0));
        }

        for(uint256 i=rd;i<rd+mid;i++){
            emit blockHashEvent(sha256(abi.encode(i)));
        }
        for(uint256 i=0;i<end;i++){
            emit blockHashEvent(bytes32(0));
        }
    }
#### repo
https://github.com/cryptape/evm-testing/blob/master/test/bug/bug.list.test.js#L8-L15
```
git clone https://github.com/cryptape/evm-testing.git
npm install
// localhost:8024
npm run test:test --network=gw_local_kit_net_v1 --grep="279"
// https://godwoken-betanet-v1.ckbapp.dev
npm run test:test --network=gw_testnet_v11 --grep="279"
```
#### test 
step
1. deploy contract 
2. invoke testEvent(2,7,1,17500,{gasLimit:"0x989680"})
3. query tx receipt

#### test code 
```SOL
it("out of gas tx",async ()=>{
        let eventTestContractInfo = await ethers.getContractFactory("eventTestContract");
        contract = await eventTestContractInfo.deploy()
        await contract.deployed()
        let tx = await contract.testEvent(2,7,1,17500,{gasLimit:"0x989680"})
        let response = await getTxReceipt(ethers.provider,tx.hash,10)
        expect(response.status).to.be.equal(0)
}).timeout(60000)
```
#### response
https://godwoken-betanet-v1.ckbapp.dev
https://v1.betanet.gwscan.com/zh-CN/tx/0xc94db18b706b711f01cae5106e2543dcaf44e32ab763e6ca1e3849282ca3d76b?search=0xc94db18b706b711f01cae5106e2543dcaf44e32ab763e6ca1e3849282ca3d76b

#### kicker
```
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_getTransactionByHash',
  params: [
    '0xa34c3ccc344cec5672b788f80146ad9f87740ef684f6d5243ea25ae28a76d9a5'
  ],
  id: 101
}
jsonRpcResponse: { jsonrpc: '2.0', id: 101, result: null }

Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/guopenglin/WebstormProjects/gp/evm-testing/test/bug/bug.list.test.js)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

**Comment by classicalliu** [comment]
![image](https://user-images.githubusercontent.com/13375784/173758924-d4c013cb-3fa1-47c1-9015-e519152830a6.png)

Seems dropped by godwoken @jjyr
