### ISSUE TITLE
Failed to deploy a devnet with Godwoken-Kicker

### ISSUE THREAD

**Issue by Flouse** [RetricSu/godwoken-kicker#299]
doc: https://docs.godwoken.io/deployLocalNetwork/

docker-compose version 1.29.2, build 5becea4c

![image](https://user-images.githubusercontent.com/1297478/185352766-0c35b44b-51af-499b-b962-c981c7cfbbf9.png)

docker-compose logs -f godwoken show errors below:
![image](https://user-images.githubusercontent.com/1297478/185352800-b86354f6-9a69-414f-a752-a5f007258945.png)

**Comment by keroro520** [comment]
I cannot find the root cause according to the above picture. It might be because the released binary cannot run on your machine due to hardware issues.
It would be very helpful that provides the full logs, by `./kicker logs > kicker.log`.

**Comment by keroro520** [comment]
@xiadd Thanks!

![2022-08-19 at 11 14 AM](https://user-images.githubusercontent.com/1870648/185535034-714c0020-add8-4e36-a5e0-132c6e44dda4.jpg)

@Flouse @sopium Can you help explain this issue?

**Comment by sopium** [comment]
The godwoken/gw-tools binaries in published docker images need AVX2, which could be missing in your VM:

https://github.com/sopium/godwoken-docker-prebuilds#cpu-feature-requirement

For now you need to build godwoken manually.

@Flouse maybe we should use “CPU portable” binaries/images in kicker for better compatibility?

**Comment by keroro520** [comment]
> 

@xiadd 
There is another issue here. The logs indicate that the CKB container is having trouble, or the connections to the CKB container are having trouble.
Please use the below commands to obtain more info about the CKB container:

**Comment by keroro520** [comment]
@xiadd 

The CKB container is running, while CKB Indexer and CKB Miner cannot connect to it, and `curl` http://localhost:8114 fails as well.
Docker Compose might not handle container connections correctly. We have nothing to do but restart Kicker:

```
./kicker stop
./kicker start
```

**Comment by keroro520** [comment]
> @xiadd
> 
> The CKB container is running, while CKB Indexer and CKB Miner cannot connect to it, and `curl` http://localhost:8114 fails as well. Docker Compose might not handle container connections correctly. We have nothing to do but restart Kicker:
> 
> ```
> ./kicker stop
> ./kicker start
> ```

Or even restart Docker Compose.

**Comment by keroro520** [comment]
I'm happy to help.
