### ISSUE TITLE
MetaMask transactions stuck in Pending state

### ISSUE THREAD

**Issue by Kuzirashi** [RetricSu/godwoken-kicker#32]
After sending MetaMask transaction it's often stuck in pending mode on Godwoken network. Me and the second independent team were able to reproduce.

**Comment by RetricSu** [comment]
two possible reason:

1. the web3 component hit some issue. metamask is connecting to this very web3 rpc server. you can checkout the logs `make web3` 
2. network issue. network got lost with web3 server during the process. this should be handle with more persistent way to checking result.

for now, suggest doing:

after encounter this issue, clean the metamask data (setting -> advance -> reset account) and try again.

**Comment by Kuzirashi** [comment]
After latest version I'm not hitting this error that often anymore. Seems like it's more stable 👍
