### ISSUE TITLE
Calling view function that gets `block.chainid` fails with "Internal JSON-RPC error." (error code 14)

### ISSUE THREAD

**Issue by Kuzirashi** [RetricSu/godwoken-kicker#39]
Having a deployed contract with such function:
```
function getChainId() external view returns (uint256) {
        return block.chainid;
}
```

And trying to call:
```
contract.methods.getChainId().call()
```

Results in:
![image](https://user-images.githubusercontent.com/4950658/119524578-11608800-bd7e-11eb-9ff8-d37187aa0bfc.png)

"MetaMask - RPC Error: Internal JSON-RPC error."

Godwoken log: https://gist.github.com/Kuzirashi/a740d7f9a6e337cc25589f726198ef2e

Context:

1. It is working in Ganache.
2. Reason why I'm testing this is I'm trying to implement full cycle of using https://eips.ethereum.org/EIPS/eip-712 in application.

**Comment by RetricSu** [comment]
@TheWaWaR pls take a look

**Comment by RetricSu** [comment]
would you please provide the full source code of this contract?

**Comment by Kuzirashi** [comment]
I think I've tested it on the wrong deployed contract... Sorry for the confusion. @RetricSu

**Comment by Kuzirashi** [comment]
Okay, I tested again and this time I made sure I'm testing correct contract. I get an error:
```
(node:17190) UnhandledPromiseRejectionWarning: Error: Returned error: Internal error
```

Later I can see error status code is 14. 

I have open-source repo that you can use to reproduce and find contract: https://github.com/Kuzirashi/blockchain-workshop/tree/godwoken (branch godwoken, commit: cb8659866c3d25bb3cc64b13f7dc0ecbab5f022e).

First, start Godwoken network and then you can use following commands to reproduce this issue:
```
yarn && yarn build && yarn start
```

Deploying contract will work, but it will error during call to `getChainId`. It works fine on Ganache (Ethereum).

TypeScript code (src/HeadTail.ts):
```
const CHAIN_ID = parseInt(await headTail.methods.getChainId().call(), 10);
```

Full Solidity smart-contract: https://github.com/Kuzirashi/blockchain-workshop/blob/cb8659866c3d25bb3cc64b13f7dc0ecbab5f022e/contracts/HeadTail.sol

Web3 log:
```
web3_1       | POST / 200 1.705 ms - 913
web3_1       | eth contract address: 0x0f5e55b42c803e3a0cc1fea3f622b98f08000000, account id: 8
web3_1       | POST / 200 4.503 ms - 17673
web3_1       | eth contract address: 0x0f5e55b42c803e3a0cc1fea3f622b98f08000000, account id: 8
web3_1       | rawL2Transaction: {
web3_1       |   "from_id": "0x0",
web3_1       |   "to_id": "0x8",
web3_1       |   "nonce": "0x0",
web3_1       |   "args": "0xffffff504f4c590000000001000000000100000000000000000000000000000000000000000000000000000000000000040000003408e470"
web3_1       | }
web3_1       | [error]  JSONRPC Server Error: [bound call] Error: JSONRPCError: server error {"code":0,"message":"invalid exit code 14"} Error: JSONRPCError: server error {"code":0,"message":"invalid exit code 14"}
web3_1       |     at Proxy.<anonymous> (/godwoken-web3/node_modules/ckb-js-toolkit/dist/ckb-js-toolkit.node.js:1:51999)
web3_1       |     at runMicrotasks (<anonymous>)
web3_1       |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
web3_1       |     at async Eth.call (/godwoken-web3/packages/api-server/lib/methods/modules/eth.js:243:27)
web3_1       |     at async Eth.call (/godwoken-web3/packages/api-server/lib/methods/validator.js:32:20)
```

Godwoken log: https://gist.github.com/Kuzirashi/acdf588011a56d12651cf1fcf6b5a690 

Interesting fragment:
```
godwoken_1   | [2021-05-26T10:57:27Z DEBUG gw_generator::syscalls] [contract debug]: pay fee to block_producer failed => 14
```

It's interesting because I'm calling view function, which doesn't need to pay fees.

**Comment by TheWaWaR** [comment]
@Kuzirashi 
How about use `gas_price = 0` which currently is allowed?

**Comment by Kuzirashi** [comment]
I changed the call to be:
```
const CHAIN_ID = parseInt(
        await headTail.methods.getChainId().call({
            gasPrice: 0
        }),
        10
    );
```

and it still fails @TheWaWaR. Same error.

**Comment by TheWaWaR** [comment]
Will be fixed in this PR.
https://github.com/nervosnetwork/godwoken-polyjuice/pull/35

**Comment by TheWaWaR** [comment]
@Kuzirashi  
Please try the latest tag.
https://github.com/nervosnetwork/godwoken-polyjuice/releases/tag/v0.6.0-rc5

**Comment by Kuzirashi** [comment]
Unfortunately it doesn't work @TheWaWaR. I've checked your code and what Godwoken receives in the logs when the transaction is sent.

Even though I use the following call in web3.js (node.js or MetaMask):
```
await headTail.methods.getChainId().call({
    gasPrice: 0
}),
```

Godwoken sees it as gasPrice 1 and fee is automatically different than 0 (in your code you added if statement when fee is 0, but here it's actually != 0). Shortened Godwoken log (you can find full Godwoken log in comment: https://github.com/RetricSu/godwoken-kicker/issues/39#issuecomment-848679254):
```
godwoken_1   | [2021-05-27T13:25:28Z DEBUG gw_generator::syscalls] [contract debug]: to_id_is_eoa => 0
godwoken_1   | [2021-05-27T13:25:28Z DEBUG gw_generator::syscalls] [contract debug]: transfer_only => 0
godwoken_1   | [2021-05-27T13:25:28Z DEBUG gw_generator::syscalls] [contract debug]: code size => 8817
godwoken_1   | [2021-05-27T13:25:28Z DEBUG gw_generator::syscalls] [contract debug]: msg.input_data 0x3408e470
godwoken_1   | [2021-05-27T13:25:28Z DEBUG gw_generator::syscalls] [contract debug]: output data 0x0000000000000000000000000000000000000000000000000000000000000003
godwoken_1   | [2021-05-27T13:25:28Z DEBUG gw_generator::syscalls] [contract debug]: output size => 32
godwoken_1   | [2021-05-27T13:25:28Z DEBUG gw_generator::syscalls] [contract debug]: status_code => 0
godwoken_1   | [2021-05-27T13:25:28Z DEBUG gw_generator::syscalls] [contract debug]: END handle_message
godwoken_1   | [2021-05-27T13:25:28Z DEBUG gw_generator::syscalls] [contract debug]: gas limit => 16777216
godwoken_1   | [2021-05-27T13:25:28Z DEBUG gw_generator::syscalls] [contract debug]: gas left => 16776879
godwoken_1   | [2021-05-27T13:25:28Z DEBUG gw_generator::syscalls] [contract debug]: gas price => 1
godwoken_1   | [2021-05-27T13:25:28Z DEBUG gw_generator::syscalls] [contract debug]: fee => 337
godwoken_1   | [2021-05-27T13:25:28Z DEBUG gw_generator::syscalls] [contract debug]: pay fee to block_producer failed => 14
```

Notice fee here is 337 and gas price 1 even though in web3.js it's set to 0.

![image](https://user-images.githubusercontent.com/4950658/119834234-10576400-bf00-11eb-94c0-6813a2672cd8.png)

**Comment by Kuzirashi** [comment]
Okay, this seems to be actually a working workaround:
```
await headTail.methods.getChainId().call({
    gasPrice: '0'
}),
```

Notice I changed `gasPrice` from `0` to `'0'`. Now the call to getChainId succeeds. The question is - should this issue be still open unless there's no need to pass `gasPrice: '0'` explicitly or is it by design in Godwoken and this issue should be closed?

**Comment by RetricSu** [comment]
we don't have a conclusion on this right now. I think it is better that we keep this issue open.

**Comment by RetricSu** [comment]
https://github.com/nervosnetwork/godwoken/blob/master/docs/migrate_evm_contract_to_polyjuice.md
