### ISSUE TITLE
ERROR: Unsupported config option for services.gen-godwoken-schema: 'profiles'  in the compose file 

### ISSUE THREAD

**Issue by Flouse** [RetricSu/godwoken-kicker#64]
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.gen-godwoken-schema: 'profiles'
make: *** [Makefile:88: start] Error 1

https://github.com/RetricSu/godwoken-kicker/blob/2bdeae20f5ccad98176463f71703df73ed8c9e91/docker/docker-compose.yml#L97

**Comment by RetricSu** [comment]
update your docker-compose version to latest should solve the problem. later we might remove this feature.
